Repository camunda/camunda-bpmn-js, pull requests merged in 2024-11, with the labels that each got.

#388 Bump development dependencies (house keeping)
  package-lock.json
  package.json
Labels: needs review, dependencies

#391 Support task listeners
  CHANGELOG.md
  package-lock.json
  package.json
Labels: needs review

#392 deps: update to camunda-bpmn-js-behaviors@1.7.2
  CHANGELOG.md
  package-lock.json
  package.json
Labels: in progress
